### ISSUE TITLE
Unable to switch to a child window that Pops Up upon clicking the Next Button from the main window

### ISSUE THREAD

**Issue by EKTACHUNNI** [EKTACHUNNI/AutomationWorkspace#1]
I am using **pywinauto** for automation of a Windows Desktop based Application with (backend=uia)

Clicking Next Button from Main Window Pops up a child window , and unable to click Accept Button in the child Window as the control does not seem to be switching from Main Window , got below error:-

Traceback (most recent call last): File "C:/xxxx", line 60, in app.xxx.Next.click() #click next from GridTableView Window File "C:`xxxx.py", line 121, in click self.invoke() File "C:\xxxx\uiawrapper.py", line 513, in invoke self.iface`_invoke.Invoke() _ctypes.COMError: (-2146233083, None, (None, None, None, 0, None))

Tried using below piece of code for switching the control to child window but it does not work :

app.window(auto_id="TitleBar").window(class_name="WindowsForms10.Window.x.x.xxxx").children()[3].click()

Any help will be very much appreciated, thanks. @pywinauto @vasily-v-ryabov

**Comment by EKTACHUNNI** [comment]
This was not a Pop Up as the title is still main window and managed to click button from main window control itself, hence closing the issue.
